name: SVN-to-Git-Hub-Migration

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: self-hosted # You can choose other OS if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace with the desired Python version


      - name: Run Python script
        run: |
          python3 -m pip install --upgrade pip
          #pip3 install --user -r requirements.txt  # If your script has any dependencies, list them in requirements.txt
          python3 pyt.py
